"""add reading log

Revision ID: 0d6879d246d6
Revises: b4e05a8fb1c0
Create Date: 2026-09-28 14:36:23.334320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6879d246d6'
down_revision: Union[str, Sequence[str], None] = 'b4e05a8fb1c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('finished_at', sa.Date(), nullable=True),
    sa.Column('is_reread', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_logs_book_id'), 'reading_logs', ['book_id'], unique=False)
    op.create_index(op.f('ix_reading_logs_id'), 'reading_logs', ['id'], unique=False)
    op.create_index(op.f('ix_reading_logs_user_id'), 'reading_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reading_logs_user_id'), table_name='reading_logs')
    op.drop_index(op.f('ix_reading_logs_id'), table_name='reading_logs')
    op.drop_index(op.f('ix_reading_logs_book_id'), table_name='reading_logs')
    op.drop_table('reading_logs')
    # ### end Alembic commands ###
