"""drop book rating, add cover_url and avatar_url

Revision ID: 58240b077c40
Revises: 5f3dcf1fd147
Create Date: 2026-09-28 14:33:25.919477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58240b077c40'
down_revision: Union[str, Sequence[str], None] = '5f3dcf1fd147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('cover_url', sa.String(length=500), nullable=True))
    op.drop_column('books', 'rating')
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.add_column('books', sa.Column('rating', sa.FLOAT(), nullable=False))
    op.drop_column('books', 'cover_url')
    # ### end Alembic commands ###
